name = "forma"
compatibility_date = "2024-01-01"

[env.production]
name = "forma"

[env.preview]
name = "forma-preview"

# Environment variables
[vars]
NEXT_PUBLIC_BASE_URL = "https://forma-design.com"
